In [3]:
import keras

2024-09-09 07:05:49.964201: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [11]:
from IPython.display import clear_output
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras import optimizers
#import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import StratifiedKFold
#from xgboost import XGBClassifier

In [10]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.ensemble import VotingClassifier
from keras.regularizers import l2
from numpy import mean
from numpy import std
from numpy import array
from numpy import argmax
#from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix
import itertools
import pickle
#import matplotlib.pyplot as plt
from keras.utils import to_categorical
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import roc_auc_score
#from matplotlib import pyplot
from sklearn.metrics import roc_curve, auc
#from scipy import interp
#import matplotlib.pyplot as plt
from itertools import cycle
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from sklearn.model_selection import KFold
#Random Number
r = 42

In [13]:
from xgboost import XGBClassifier

In [16]:
import matplotlib.pyplot as plt

In [27]:
#from imblearn.over_sampling import SMOTE
import scipy

In [34]:
#from scipy import interp

ImportError: cannot import name 'interp' from 'scipy' (/Users/manashsarma/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages/scipy/__init__.py)

In [29]:
import scipy
print(scipy.__version__)

1.13.0

In [30]:
pip install scipy==1.11.4

Requirement already satisfied: scipy==1.11.4 in /Users/manashsarma/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages (1.11.4)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /Users/manashsarma/opt/anaconda3/envs/python3.11/lib/python3.11/site-packages (from scipy==1.11.4) (1.23.5)
Note: you may need to restart the kernel to use updated packages.

In [33]:
import scipy
print(scipy.__version__)

1.13.0

In [32]:
conda install scipy==1.11.4

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 24.7.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/manashsarma/opt/anaconda3/envs/python3.11

  added / updated specs:
    - scipy==1.11.4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.11.4               |  py311h224febf_0        22.3 MB
    ------------------------------------------------------------
                                           Total:        22.3 MB

The following packages will be DOWNGRADED:

  scipy                              1.12.0-py311h224febf_0 --> 1.11.4-py311h224febf_0 None



Downloading and Extracting Packages
scipy-1.11.4         | 22.3 MB   | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [35]:
df_genes_ncbi_GSE63061 = pd.read_csv('/Users/manashsarma/Downloads/1Genomics_research/1RUAS_paper_submissions_and_helpful_book/3Gex_submission/code_geo/gse_full_output_GSE63061.csv')

In [41]:
df_genes_ncbi_GSE63061.head(2)

,Symbol,ILMN_Gene,Transcript,Entrez_Gene_ID,Chromosome,Cytoband,GSM1539409,GSM1539410,GSM1539411,GSM1539412,...,GSM1539787,GSM1539788,GSM1539789,GSM1539790,GSM1539791,GSM1539792,GSM1539793,GSM1539794,GSM1539795,GSM1539796
0,EEF1A1,EEF1A1,ILMN_5311,1915.0,6,6q13c,12.552807,12.711459,13.088393,12.643831,...,12.981682,13.639167,12.921447,13.249406,13.526591,12.311846,13.225328,12.952104,13.163361,13.347750
1,GAPDH,GAPDH,ILMN_27206,2597.0,12,12p13.31d,10.101556,9.776015,9.594397,10.126782,...,9.944963,9.536020,9.826929,10.122347,10.090682,10.523515,9.975095,9.758630,10.030987,9.633395

In [40]:
df_genes_ncbi_GSE63061.shape

(32049, 394)

In [42]:
df_genes_ncbi_GSE63060 = pd.read_csv('/Users/manashsarma/Downloads/1Genomics_research/1RUAS_paper_submissions_and_helpful_book/3Gex_submission/code_geo/GSE63060_geneExpression.csv')

In [43]:
df_genes_ncbi_GSE63060.head(2)

,Unnamed: 0,index,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,...,CD96.1,SPECC1.1,DNAJB14.4,ENOX2.2,THOC3.1,MRRF.3,KIAA1751.3,age:ch1,gender:ch1,status:ch1
0,0,GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,...,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152,65,Female,MCI
1,1,GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,...,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313,66,Female,MCI

In [44]:
df_genes_ncbi_GSE63060.shape

(329, 38328)

In [45]:
df_genes_ncbi_GSE63060_diag = pd.read_csv('/Users/manashsarma/Downloads/1Genomics_research/1RUAS_paper_submissions_and_helpful_book/3Gex_submission/code_geo/GSE63060_geneExpression_diagnosis.csv')

In [46]:
df_genes_ncbi_GSE63060_diag.head(2)

,Unnamed: 0,index,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,...,CD96.1,SPECC1.1,DNAJB14.4,ENOX2.2,THOC3.1,MRRF.3,KIAA1751.3,age:ch1,gender:ch1,status:ch1
0,0,GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,...,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152,65,Female,MCI
1,1,GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,...,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313,66,Female,MCI

In [47]:
gse_full_output2__63060_org = pd.read_csv('/Users/manashsarma/Downloads/gse_full_output2__63060_org.csv')

/var/folders/bq/sdm0wvbs55vgz21fqdplwghm0000gn/T/ipykernel_10593/436759425.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  gse_full_output2__63060_org = pd.read_csv('/Users/manashsarma/Downloads/gse_full_output2__63060_org.csv')

In [48]:
gse_full_output2__63060_org.head(2)

,Symbol,ILMN_Gene,Transcript,Entrez_Gene_ID,Chromosome,Cytoband,GSM1539080,GSM1539081,GSM1539082,GSM1539083,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
0,EEF1A1,EEF1A1,ILMN_5311,1915.0,6,6q13c,14.611769,14.427104,14.624553,14.442078,...,14.668559,14.526182,14.695354,15.049790,14.025296,14.915290,14.655069,14.869782,14.249922,14.891158
1,GAPDH,GAPDH,ILMN_27206,2597.0,12,12p13.31d,11.944514,11.930664,11.777748,12.420057,...,12.126935,11.892791,12.043099,12.019189,12.049508,12.104508,11.903194,11.560549,11.625297,12.064573

In [49]:
gse_full_output__63060_org = pd.read_csv('/Users/manashsarma/Downloads/gse_full_output__63060_org.csv', low_memory=False)

In [50]:
gse_full_output__63060_org.head(2)

,Symbol,Entrez_Gene_ID,Chromosome,Cytoband,GSM1539080,GSM1539081,GSM1539082,GSM1539083,GSM1539084,GSM1539085,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
0,EEF1A1,1915.0,6,6q13c,14.611769,14.427104,14.624553,14.442078,14.127102,14.412088,...,14.668559,14.526182,14.695354,15.049790,14.025296,14.915290,14.655069,14.869782,14.249922,14.891158
1,GAPDH,2597.0,12,12p13.31d,11.944514,11.930664,11.777748,12.420057,11.725034,11.941696,...,12.126935,11.892791,12.043099,12.019189,12.049508,12.104508,11.903194,11.560549,11.625297,12.064573

In [51]:
gse_full_output__63060_org.head(5)

,Symbol,Entrez_Gene_ID,Chromosome,Cytoband,GSM1539080,GSM1539081,GSM1539082,GSM1539083,GSM1539084,GSM1539085,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
0,EEF1A1,1915.0,6,6q13c,14.611769,14.427104,14.624553,14.442078,14.127102,14.412088,...,14.668559,14.526182,14.695354,15.049790,14.025296,14.915290,14.655069,14.869782,14.249922,14.891158
1,GAPDH,2597.0,12,12p13.31d,11.944514,11.930664,11.777748,12.420057,11.725034,11.941696,...,12.126935,11.892791,12.043099,12.019189,12.049508,12.104508,11.903194,11.560549,11.625297,12.064573
2,SLC35E2,9906.0,1,1p36.33a,7.517737,7.546532,7.647790,7.745140,7.520212,7.716517,...,7.607597,7.622884,7.635975,7.699531,7.649240,7.636703,7.605595,7.581313,7.587167,7.614630
3,LOC642820,642820.0,10,NaN,7.419066,7.403191,7.382467,7.438868,7.430150,7.441058,...,7.419287,7.395029,7.404132,7.455708,7.435492,7.462115,7.498538,7.470538,7.511239,7.509601
4,RPS28,6234.0,19,19p13.2d,11.507170,10.506885,12.058497,10.649464,11.958259,10.947954,...,11.016573,11.178761,10.796267,10.828405,10.375336,10.188892,11.489647,11.358234,10.361057,10.521751

In [52]:
df_genes_ncbi_GSE63061=df_genes_ncbi_GSE63061.drop(['Symbol','Transcript','Entrez_Gene_ID',
                                                                'Chromosome','Cytoband'], axis = 1)
df_genes_ncbi_GSE63061.head()

,ILMN_Gene,GSM1539409,GSM1539410,GSM1539411,GSM1539412,GSM1539413,GSM1539414,GSM1539415,GSM1539416,GSM1539417,...,GSM1539787,GSM1539788,GSM1539789,GSM1539790,GSM1539791,GSM1539792,GSM1539793,GSM1539794,GSM1539795,GSM1539796
0,EEF1A1,12.552807,12.711459,13.088393,12.643831,13.098389,13.086100,13.400343,12.974184,13.275410,...,12.981682,13.639167,12.921447,13.249406,13.526591,12.311846,13.225328,12.952104,13.163361,13.347750
1,GAPDH,10.101556,9.776015,9.594397,10.126782,10.223301,9.827239,9.944569,9.951156,9.872258,...,9.944963,9.536020,9.826929,10.122347,10.090682,10.523515,9.975095,9.758630,10.030987,9.633395
2,SLC35E2,6.084671,6.255012,6.160485,6.109219,6.069960,6.149266,6.179737,6.212482,6.110075,...,6.119649,6.073826,6.080492,6.189363,6.083447,6.282546,6.000918,6.146775,6.198628,6.051466
3,DUSP22,6.068805,6.016468,6.024322,6.016118,6.056163,6.049337,6.017571,6.013845,6.033241,...,6.089997,6.014776,6.052894,6.042398,6.046160,6.011261,6.017957,6.023580,6.049709,6.038705
4,LOC642820,6.121060,6.173167,6.039552,6.111306,6.089542,6.046485,6.109781,6.118480,6.104469,...,6.073604,6.064816,6.115535,6.076337,6.020126,6.094986,6.094835,6.051846,6.110575,6.032558

In [53]:
df_genes_ncbi_GSE63061.T.head()

,0,1,2,3,4,5,6,7,8,9,...,32039,32040,32041,32042,32043,32044,32045,32046,32047,32048
ILMN_Gene,EEF1A1,GAPDH,SLC35E2,DUSP22,LOC642820,RPS28,IPO13,AFAP1,CDT1,LPP,...,MIR335,MIR663B,FOXO6,MGC11082,BEYLA,FOXO6,NCRNA00173,SKCG-1,SKCG-1,NCRNA00173
GSM1539409,12.552807,10.101556,6.084671,6.068805,6.12106,10.833984,6.617146,6.126976,6.062613,9.271763,...,6.04762,6.191827,6.132717,6.168559,6.064898,6.095934,6.200839,6.004514,6.045534,6.251677
GSM1539410,12.711459,9.776015,6.255012,6.016468,6.173167,10.270673,6.590062,6.081223,6.013171,9.038845,...,6.08059,6.204891,6.032577,6.02194,6.081256,6.08884,6.394213,5.988105,6.037021,6.164831
GSM1539411,13.088393,9.594397,6.160485,6.024322,6.039552,10.430594,6.509477,6.081791,6.012163,9.059376,...,6.0661,5.988669,6.116726,6.022835,6.044907,6.145017,6.086684,6.066209,6.098268,6.284407
GSM1539412,12.643831,10.126782,6.109219,6.016118,6.111306,10.765207,6.570108,6.07593,6.04603,9.080949,...,6.153731,6.064466,6.020922,6.137347,6.031711,6.035403,6.270068,6.005295,6.032477,6.350185

In [54]:
df_genes_ncbi_GSE63061 = df_genes_ncbi_GSE63061.set_index(['ILMN_Gene'])

In [55]:
df_genes_ncbi_GSE63061.T.head()

ILMN_Gene,EEF1A1,GAPDH,SLC35E2,DUSP22,LOC642820,RPS28,IPO13,AFAP1,CDT1,LPP,...,MIR335,MIR663B,FOXO6,MGC11082,BEYLA,FOXO6,NCRNA00173,SKCG-1,SKCG-1,NCRNA00173
GSM1539409,12.552807,10.101556,6.084671,6.068805,6.121060,10.833984,6.617146,6.126976,6.062613,9.271763,...,6.047620,6.191827,6.132717,6.168559,6.064898,6.095934,6.200839,6.004514,6.045534,6.251677
GSM1539410,12.711459,9.776015,6.255012,6.016468,6.173167,10.270673,6.590062,6.081223,6.013171,9.038845,...,6.080590,6.204891,6.032577,6.021940,6.081256,6.088840,6.394213,5.988105,6.037021,6.164831
GSM1539411,13.088393,9.594397,6.160485,6.024322,6.039552,10.430594,6.509477,6.081791,6.012163,9.059376,...,6.066100,5.988669,6.116726,6.022835,6.044907,6.145017,6.086684,6.066209,6.098268,6.284407
GSM1539412,12.643831,10.126782,6.109219,6.016118,6.111306,10.765207,6.570108,6.075930,6.046030,9.080949,...,6.153731,6.064466,6.020922,6.137347,6.031711,6.035403,6.270068,6.005295,6.032477,6.350185
GSM1539413,13.098389,10.223301,6.069960,6.056163,6.089542,10.632346,6.515033,6.089809,6.050976,8.761323,...,6.061074,6.075910,6.141739,6.019399,6.036910,6.054054,6.280061,6.043561,6.151250,6.190593

In [56]:
df_genes_ncbi_GSE63061=df_genes_ncbi_GSE63061.T

In [57]:
df_genes_ncbi_GSE63061.head()

ILMN_Gene,EEF1A1,GAPDH,SLC35E2,DUSP22,LOC642820,RPS28,IPO13,AFAP1,CDT1,LPP,...,MIR335,MIR663B,FOXO6,MGC11082,BEYLA,FOXO6,NCRNA00173,SKCG-1,SKCG-1,NCRNA00173
GSM1539409,12.552807,10.101556,6.084671,6.068805,6.121060,10.833984,6.617146,6.126976,6.062613,9.271763,...,6.047620,6.191827,6.132717,6.168559,6.064898,6.095934,6.200839,6.004514,6.045534,6.251677
GSM1539410,12.711459,9.776015,6.255012,6.016468,6.173167,10.270673,6.590062,6.081223,6.013171,9.038845,...,6.080590,6.204891,6.032577,6.021940,6.081256,6.088840,6.394213,5.988105,6.037021,6.164831
GSM1539411,13.088393,9.594397,6.160485,6.024322,6.039552,10.430594,6.509477,6.081791,6.012163,9.059376,...,6.066100,5.988669,6.116726,6.022835,6.044907,6.145017,6.086684,6.066209,6.098268,6.284407
GSM1539412,12.643831,10.126782,6.109219,6.016118,6.111306,10.765207,6.570108,6.075930,6.046030,9.080949,...,6.153731,6.064466,6.020922,6.137347,6.031711,6.035403,6.270068,6.005295,6.032477,6.350185
GSM1539413,13.098389,10.223301,6.069960,6.056163,6.089542,10.632346,6.515033,6.089809,6.050976,8.761323,...,6.061074,6.075910,6.141739,6.019399,6.036910,6.054054,6.280061,6.043561,6.151250,6.190593

In [58]:
df_genes_ncbi_GSE63061.head(2)

ILMN_Gene,EEF1A1,GAPDH,SLC35E2,DUSP22,LOC642820,RPS28,IPO13,AFAP1,CDT1,LPP,...,MIR335,MIR663B,FOXO6,MGC11082,BEYLA,FOXO6,NCRNA00173,SKCG-1,SKCG-1,NCRNA00173
GSM1539409,12.552807,10.101556,6.084671,6.068805,6.121060,10.833984,6.617146,6.126976,6.062613,9.271763,...,6.04762,6.191827,6.132717,6.168559,6.064898,6.095934,6.200839,6.004514,6.045534,6.251677
GSM1539410,12.711459,9.776015,6.255012,6.016468,6.173167,10.270673,6.590062,6.081223,6.013171,9.038845,...,6.08059,6.204891,6.032577,6.021940,6.081256,6.088840,6.394213,5.988105,6.037021,6.164831

In [59]:
df_genes_ncbi_GSE63061.shape

(388, 32049)

In [61]:
GSE63061_samples_df = pd.read_csv('./gse_GSE63061_samples.csv')

In [62]:
GSE63061_samples_df.head()

,title,geo_accession,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,characteristics_ch1,...,contact_zip/postal_code,contact_country,supplementary_file,data_row_count,age:ch1,ethnicity:ch1,gender:ch1,included in case -control study:ch1,status:ch1,tissue:ch1
0,7196843065_F,GSM1539409,Public on Aug 05 2015,Nov 06 2014,May 30 2024,RNA,1,Blood,Homo sapiens,status: MCI,...,FK9 4AX,United Kingdom,NONE,32049,57,Western European,Female,yes,MCI,blood
1,7196843076_G,GSM1539410,Public on Aug 05 2015,Nov 06 2014,May 30 2024,RNA,1,Blood,Homo sapiens,status: MCI,...,FK9 4AX,United Kingdom,NONE,32049,59,Western European,Female,yes,MCI,blood
2,7196843068_B,GSM1539411,Public on Aug 05 2015,Nov 06 2014,May 30 2024,RNA,1,Blood,Homo sapiens,status: MCI,...,FK9 4AX,United Kingdom,NONE,32049,63,Western European,Female,yes,MCI,blood
3,7196843063_B,GSM1539412,Public on Aug 05 2015,Nov 06 2014,May 30 2024,RNA,1,Blood,Homo sapiens,status: MCI,...,FK9 4AX,United Kingdom,NONE,32049,65,Western European,Female,yes,MCI,blood
4,7196843065_L,GSM1539413,Public on Aug 05 2015,Nov 06 2014,May 30 2024,RNA,1,Blood,Homo sapiens,status: MCI,...,FK9 4AX,United Kingdom,NONE,32049,66,Other Caucasian,Female,yes,MCI,blood

In [63]:
GSE63061_samples_df.shape

(388, 40)

In [64]:
GSE63061_samples_df['status:ch1'].value_counts()

AD                139
CTL               134
MCI               109
borderline MCI      3
OTHER               1
CTL to AD           1
MCI to CTL          1
Name: status:ch1, dtype: int64

In [66]:
GSE63061_samples_df.index

RangeIndex(start=0, stop=388, step=1)

In [69]:
GSE63061_samples_df = GSE63061_samples_df[['geo_accession', 'age:ch1', 	'gender:ch1' ,	'status:ch1' ]]

In [70]:
GSE63061_samples_df.head()

  geo_accession  age:ch1 gender:ch1 status:ch1
0    GSM1539409       57     Female        MCI
1    GSM1539410       59     Female        MCI
2    GSM1539411       63     Female        MCI
3    GSM1539412       65     Female        MCI
4    GSM1539413       66     Female        MCI

In [71]:
GSE63061_samples_df.rename(columns = {'geo_accession':'ILMN_Gene'}, inplace = True)

/var/folders/bq/sdm0wvbs55vgz21fqdplwghm0000gn/T/ipykernel_10593/3137077445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GSE63061_samples_df.rename(columns = {'geo_accession':'ILMN_Gene'}, inplace = True)

In [72]:
GSE63061_samples_df.head()

    ILMN_Gene  age:ch1 gender:ch1 status:ch1
0  GSM1539409       57     Female        MCI
1  GSM1539410       59     Female        MCI
2  GSM1539411       63     Female        MCI
3  GSM1539412       65     Female        MCI
4  GSM1539413       66     Female        MCI

In [74]:
df_genes_ncbi_GSE63061.index

Index(['GSM1539409', 'GSM1539410', 'GSM1539411', 'GSM1539412', 'GSM1539413',
       'GSM1539414', 'GSM1539415', 'GSM1539416', 'GSM1539417', 'GSM1539418',
       ...
       'GSM1539787', 'GSM1539788', 'GSM1539789', 'GSM1539790', 'GSM1539791',
       'GSM1539792', 'GSM1539793', 'GSM1539794', 'GSM1539795', 'GSM1539796'],
      dtype='object', length=388)

In [75]:
GSE63061_samples_df.index

RangeIndex(start=0, stop=388, step=1)

In [76]:
df_genes_ncbi_GSE63061.reset_index(inplace=True)

In [77]:
df_genes_ncbi_GSE63061.head()

ILMN_Gene,index,EEF1A1,GAPDH,SLC35E2,DUSP22,LOC642820,RPS28,IPO13,AFAP1,CDT1,...,MIR335,MIR663B,FOXO6,MGC11082,BEYLA,FOXO6,NCRNA00173,SKCG-1,SKCG-1,NCRNA00173
0,GSM1539409,12.552807,10.101556,6.084671,6.068805,6.121060,10.833984,6.617146,6.126976,6.062613,...,6.047620,6.191827,6.132717,6.168559,6.064898,6.095934,6.200839,6.004514,6.045534,6.251677
1,GSM1539410,12.711459,9.776015,6.255012,6.016468,6.173167,10.270673,6.590062,6.081223,6.013171,...,6.080590,6.204891,6.032577,6.021940,6.081256,6.088840,6.394213,5.988105,6.037021,6.164831
2,GSM1539411,13.088393,9.594397,6.160485,6.024322,6.039552,10.430594,6.509477,6.081791,6.012163,...,6.066100,5.988669,6.116726,6.022835,6.044907,6.145017,6.086684,6.066209,6.098268,6.284407
3,GSM1539412,12.643831,10.126782,6.109219,6.016118,6.111306,10.765207,6.570108,6.075930,6.046030,...,6.153731,6.064466,6.020922,6.137347,6.031711,6.035403,6.270068,6.005295,6.032477,6.350185
4,GSM1539413,13.098389,10.223301,6.069960,6.056163,6.089542,10.632346,6.515033,6.089809,6.050976,...,6.061074,6.075910,6.141739,6.019399,6.036910,6.054054,6.280061,6.043561,6.151250,6.190593

In [78]:
GSE63061_samples_df.rename(columns = {'ILMN_Gene':'index'}, inplace = True)

/var/folders/bq/sdm0wvbs55vgz21fqdplwghm0000gn/T/ipykernel_10593/2071814469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GSE63061_samples_df.rename(columns = {'ILMN_Gene':'index'}, inplace = True)

In [79]:
GSE63061_samples_df.head()

        index  age:ch1 gender:ch1 status:ch1
0  GSM1539409       57     Female        MCI
1  GSM1539410       59     Female        MCI
2  GSM1539411       63     Female        MCI
3  GSM1539412       65     Female        MCI
4  GSM1539413       66     Female        MCI

In [80]:
df_genes_ncbi_GSE63061_df=df_genes_ncbi_GSE63061.merge(GSE63061_samples_df, on=['index'])

In [81]:
df_genes_ncbi_GSE63061_df.head()

,index,EEF1A1,GAPDH,SLC35E2,DUSP22,LOC642820,RPS28,IPO13,AFAP1,CDT1,...,MGC11082,BEYLA,FOXO6,NCRNA00173,SKCG-1,SKCG-1,NCRNA00173,age:ch1,gender:ch1,status:ch1
0,GSM1539409,12.552807,10.101556,6.084671,6.068805,6.121060,10.833984,6.617146,6.126976,6.062613,...,6.168559,6.064898,6.095934,6.200839,6.004514,6.045534,6.251677,57,Female,MCI
1,GSM1539410,12.711459,9.776015,6.255012,6.016468,6.173167,10.270673,6.590062,6.081223,6.013171,...,6.021940,6.081256,6.088840,6.394213,5.988105,6.037021,6.164831,59,Female,MCI
2,GSM1539411,13.088393,9.594397,6.160485,6.024322,6.039552,10.430594,6.509477,6.081791,6.012163,...,6.022835,6.044907,6.145017,6.086684,6.066209,6.098268,6.284407,63,Female,MCI
3,GSM1539412,12.643831,10.126782,6.109219,6.016118,6.111306,10.765207,6.570108,6.075930,6.046030,...,6.137347,6.031711,6.035403,6.270068,6.005295,6.032477,6.350185,65,Female,MCI
4,GSM1539413,13.098389,10.223301,6.069960,6.056163,6.089542,10.632346,6.515033,6.089809,6.050976,...,6.019399,6.036910,6.054054,6.280061,6.043561,6.151250,6.190593,66,Female,MCI

In [82]:
df_genes_ncbi_GSE63061_df.to_csv('./df_genes_ncbi_GSE63061_diagnosis.csv')

In [97]:
#df_genes_ncbi_GSE63061_df.iloc[df_genes_ncbi_GSE63061_df.columns.duplicated()]

In [94]:
df_genes_ncbi_GSE63061_df.shape

(388, 32053)

In [1]:
from numpy import loadtxt
from xgboost import XGBClassifier
from xgboost import plot_importance
from matplotlib import pyplot

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.